export const resume = {
  name: 'Evan McDowell',
  info: {
    label: 'Software Engineer',
    image: '',
    brief:
      'I am a passionate, creative, dynamic, curious Software Engineer. I am always pursuing new technologies, frameworks and libraries, and I have an excellent attention to detail.',
  },
  contact: {
    email: 'evanmcdowell31@gmail.com',
    phone: '(850) 321-8292',
    website: '',
    other: [],
  },
  meta: {
    format: 'FRESH@^1.0.0-beta',
    modified: '2018-08-03T13:23:33.352Z',
  },
  employment: {
    history: [
      {
        position: 'Software Engineer',
        employer: 'TATA Consultancy Services',
        summary: '',
        current: true,
        start: '2017',
        url: 'https://www.tcs.com/',
        keywords: [],
        highlights: [
          'Building Retail Enterprise Tasking and Communications Mobile/Web App from scratch with Full Javascript Stack including React, NodeJS, GraphQL, MongoDB, Google Cloud Platform and Pivotal Cloud Foundry',
          "Refactored Retail Enterprise Data Application's full stack from Angular, Java to React, NodeJS, GraphQL, MongoDB, including Google Cloud, Pivotal Cloud Foundry, and Data transfromation and migration Pipelines in SQL",
          'Developed Front End Dashboard Application in Angular 2 for graphically displaying retail sales data for client Application Support Team',
          'Java training and group project - created a JSP based Cable Package Subscription web page with Identity Access Management.',
          'AWS Accredited Certifications',
          'SAFe Certified - Scaled Agile Framework Certified',
        ],
      },
      {
        position: 'IT Helpdesk',
        employer:
          'Department of Business and Professional Regulation at State of FL',
        summary:
          'Managed Help Desk tickets and DBPR employees with Active Directory and SCCM.',
        start: '2017',
        end: '2017',
        url: 'http://www.myfloridalicense.com/DBPR/',
        keywords: [],
        highlights: [],
      },
    ],
  },
  education: {
    level: '',
    history: [
      {
        level: 'Bachelor of Arts',
        institution: 'Florida State University',
        location: 'Tallahassee, Florida',
        start: '',
        end: '2017',
        grade: '',
        curriculum: [
          'C++',
          'C',
          'Java',
          'Python',
          'Software Engineering',
          'Data Structures',
          'Databases',
          'Operating Systems',
          'Unix',
        ],
        summary: 'Computer Science with a Communication minor',
      },
      {
        level: 'Associate of Arts',
        institution: 'Tallahassee Community College',
        location: 'Tallahassee, Florida',
        start: '',
        end: '2014',
        grade: '',
        curriculum: [],
        summary: '',
      },
    ],
  },
  service: {},
  skills: {
    sets: [
      {
        name: 'Frontend Development',
        level: '',
        skills: [
          'React',
          'Angular',
          'Javascript',
          'ES6',
          'Webpack',
          'babel',
          'Typescript',
          'Redux',
          'HTML5',
          'CSS',
          'GraphQL',
          "RESTful API's",
        ],
      },
      {
        name: 'Backend Development',
        level: '',
        skills: [
          'Javascript',
          'NodeJS',
          'ExpressJS',
          'MongoDB',
          'MySQL',
          'Ruby',
          'Python',
          'Java',
          'C++',
        ],
      },
      {
        name: 'Tools and others',
        level: '',
        skills: [
          'Cloud Computing',
          'Amazon Web Services',
          'Google Cloud Platform',
          'Microservices',
          'Jenkins',
          'Linux',
          'VS Code',
          'Sublime Text',
          'Github',
          'Agile development',
          'Continuous integration',
          'Continuous Deployment',
          'Slack',
        ],
      },
    ],
  },
  social: [
    {
      label: 'GitHub',
      network: 'GitHub',
      url: 'https://github.com/evanmcdowell31',
      user: 'evanmcdowell31',
    },
    {
      label: 'LinkedIn',
      network: 'LinkedIn',
      url: 'https://www.linkedin.com/in/evan-mcdowell-781536b0/',
      user: 'Evan McDowell',
    },
  ],
  interests: [
    {
      name: '',
      summary: '',
      keywords: [],
    },
  ],
  testimonials: 0,
  languages: [
    {
      language: 'English',
      level: 'native',
    },
  ],
};
